apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-films-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalogue-films
  template:
    metadata:
      labels:
        app: catalogue-films
    spec:
      containers:
        - name: catalogue
          image: timpava/react-catalogue-films:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-films-service
spec:
  selector:
    app: catalogue-films
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
